### ISSUE TITLE
The Minskins 18-01

### ISSUE THREAD

**Issue by Bismarck-GM** [jdmartinez1062/to-do#4]
### Great job building the To-Do list guys!

The project is looking excellent and, the functionality is on point!!

🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟 

![](https://media.giphy.com/media/5euCfiX7g4EVt3L76o/giphy.gif)

PS: add a gif in the readme.

**Comment by carlosveigadev** [comment]
Thanks.
